[package]
name = "apprelay"
version = "0.1.0"
authors = ["Chris Wood <chriswood@cloudflare.com>"]
edition = "2018"

[dependencies]
base64 = "0.13"
hex = "0.4"
serde_json = "1.0.82"
bytes = "1.2.0"
bhttp = { git = "https://github.com/martinthomson/ohttp", features = ["bhttp", "http"] }
ohttp = { git = "https://github.com/martinthomson/ohttp", features = ["rust-hpke", "client"], default-features = false }
futures = "0.3"
libc = "0.2"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.23"

[target.'cfg(target_os="android")'.dependencies]
jni = "0.19.0"

[build-dependencies]
cbindgen = "0.17"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
