on:
  release:
    types: [released]

jobs:

  hashes:
    name: Collect Asset Hashes
    runs-on: ubuntu-latest
    needs: [ build-ios-libraries, build-android-libraries]

    steps:

      - name: Generate hashes 
        if: startsWith(github.ref, 'refs/tags/v')
        uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: sha1
          file-name: hashes.txt

      - name: Upload asset hashes
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hashes.txt 
          asset_name:  hashes.txt
          tag: ${{ github.ref }}
